# Generated by Django 5.0.2 on 2024-04-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletAddress', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('createAt', models.CharField(max_length=300)),
            ],
        ),
    ]
