# Generated by Django 5.0.2 on 2024-04-11 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicate', '0003_predictionmodel_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionmodel',
            name='createAt',
        ),
        migrations.AddField(
            model_name='predictionmodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='model',
            field=models.CharField(max_length=300),
        ),
    ]
