# Generated by Django 5.0.2 on 2024-04-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicate', '0004_remove_predictionmodel_createat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='walletAddress',
            field=models.CharField(max_length=300),
        ),
    ]
