# Generated by Django 5.0.2 on 2024-04-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replicate', '0005_alter_usermodel_walletaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='walletAddress',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
